/**
 * @fileoverview gRPC-Web generated client stub for gaintain
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: superset.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.gaintain = require('./superset_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.gaintain.SupersetServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.gaintain.SupersetServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gaintain.SupersetsRequest,
 *   !proto.gaintain.Supersets>}
 */
const methodDescriptor_SupersetService_ListSupersets = new grpc.web.MethodDescriptor(
  '/gaintain.SupersetService/ListSupersets',
  grpc.web.MethodType.UNARY,
  proto.gaintain.SupersetsRequest,
  proto.gaintain.Supersets,
  /**
   * @param {!proto.gaintain.SupersetsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gaintain.Supersets.deserializeBinary
);


/**
 * @param {!proto.gaintain.SupersetsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gaintain.Supersets)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gaintain.Supersets>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gaintain.SupersetServiceClient.prototype.listSupersets =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gaintain.SupersetService/ListSupersets',
      request,
      metadata || {},
      methodDescriptor_SupersetService_ListSupersets,
      callback);
};


/**
 * @param {!proto.gaintain.SupersetsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gaintain.Supersets>}
 *     Promise that resolves to the response
 */
proto.gaintain.SupersetServicePromiseClient.prototype.listSupersets =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gaintain.SupersetService/ListSupersets',
      request,
      metadata || {},
      methodDescriptor_SupersetService_ListSupersets);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gaintain.NewSuperset,
 *   !proto.gaintain.Superset>}
 */
const methodDescriptor_SupersetService_CreateSuperset = new grpc.web.MethodDescriptor(
  '/gaintain.SupersetService/CreateSuperset',
  grpc.web.MethodType.UNARY,
  proto.gaintain.NewSuperset,
  proto.gaintain.Superset,
  /**
   * @param {!proto.gaintain.NewSuperset} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gaintain.Superset.deserializeBinary
);


/**
 * @param {!proto.gaintain.NewSuperset} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gaintain.Superset)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gaintain.Superset>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gaintain.SupersetServiceClient.prototype.createSuperset =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gaintain.SupersetService/CreateSuperset',
      request,
      metadata || {},
      methodDescriptor_SupersetService_CreateSuperset,
      callback);
};


/**
 * @param {!proto.gaintain.NewSuperset} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gaintain.Superset>}
 *     Promise that resolves to the response
 */
proto.gaintain.SupersetServicePromiseClient.prototype.createSuperset =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gaintain.SupersetService/CreateSuperset',
      request,
      metadata || {},
      methodDescriptor_SupersetService_CreateSuperset);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gaintain.SupersetRequest,
 *   !proto.gaintain.Superset>}
 */
const methodDescriptor_SupersetService_GetSuperset = new grpc.web.MethodDescriptor(
  '/gaintain.SupersetService/GetSuperset',
  grpc.web.MethodType.UNARY,
  proto.gaintain.SupersetRequest,
  proto.gaintain.Superset,
  /**
   * @param {!proto.gaintain.SupersetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gaintain.Superset.deserializeBinary
);


/**
 * @param {!proto.gaintain.SupersetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gaintain.Superset)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gaintain.Superset>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gaintain.SupersetServiceClient.prototype.getSuperset =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gaintain.SupersetService/GetSuperset',
      request,
      metadata || {},
      methodDescriptor_SupersetService_GetSuperset,
      callback);
};


/**
 * @param {!proto.gaintain.SupersetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gaintain.Superset>}
 *     Promise that resolves to the response
 */
proto.gaintain.SupersetServicePromiseClient.prototype.getSuperset =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gaintain.SupersetService/GetSuperset',
      request,
      metadata || {},
      methodDescriptor_SupersetService_GetSuperset);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gaintain.Superset,
 *   !proto.gaintain.Superset>}
 */
const methodDescriptor_SupersetService_UpdateSuperset = new grpc.web.MethodDescriptor(
  '/gaintain.SupersetService/UpdateSuperset',
  grpc.web.MethodType.UNARY,
  proto.gaintain.Superset,
  proto.gaintain.Superset,
  /**
   * @param {!proto.gaintain.Superset} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gaintain.Superset.deserializeBinary
);


/**
 * @param {!proto.gaintain.Superset} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gaintain.Superset)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gaintain.Superset>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gaintain.SupersetServiceClient.prototype.updateSuperset =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gaintain.SupersetService/UpdateSuperset',
      request,
      metadata || {},
      methodDescriptor_SupersetService_UpdateSuperset,
      callback);
};


/**
 * @param {!proto.gaintain.Superset} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gaintain.Superset>}
 *     Promise that resolves to the response
 */
proto.gaintain.SupersetServicePromiseClient.prototype.updateSuperset =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gaintain.SupersetService/UpdateSuperset',
      request,
      metadata || {},
      methodDescriptor_SupersetService_UpdateSuperset);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gaintain.SupersetRequest,
 *   !proto.gaintain.Superset>}
 */
const methodDescriptor_SupersetService_DeleteSuperset = new grpc.web.MethodDescriptor(
  '/gaintain.SupersetService/DeleteSuperset',
  grpc.web.MethodType.UNARY,
  proto.gaintain.SupersetRequest,
  proto.gaintain.Superset,
  /**
   * @param {!proto.gaintain.SupersetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gaintain.Superset.deserializeBinary
);


/**
 * @param {!proto.gaintain.SupersetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gaintain.Superset)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gaintain.Superset>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gaintain.SupersetServiceClient.prototype.deleteSuperset =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gaintain.SupersetService/DeleteSuperset',
      request,
      metadata || {},
      methodDescriptor_SupersetService_DeleteSuperset,
      callback);
};


/**
 * @param {!proto.gaintain.SupersetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gaintain.Superset>}
 *     Promise that resolves to the response
 */
proto.gaintain.SupersetServicePromiseClient.prototype.deleteSuperset =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gaintain.SupersetService/DeleteSuperset',
      request,
      metadata || {},
      methodDescriptor_SupersetService_DeleteSuperset);
};


module.exports = proto.gaintain;

