/**
 * @fileoverview gRPC-Web generated client stub for gaintain
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: workout.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.gaintain = require('./workout_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.gaintain.WorkoutServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.gaintain.WorkoutServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gaintain.WorkoutsRequest,
 *   !proto.gaintain.Workouts>}
 */
const methodDescriptor_WorkoutService_ListWorkouts = new grpc.web.MethodDescriptor(
  '/gaintain.WorkoutService/ListWorkouts',
  grpc.web.MethodType.UNARY,
  proto.gaintain.WorkoutsRequest,
  proto.gaintain.Workouts,
  /**
   * @param {!proto.gaintain.WorkoutsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gaintain.Workouts.deserializeBinary
);


/**
 * @param {!proto.gaintain.WorkoutsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gaintain.Workouts)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gaintain.Workouts>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gaintain.WorkoutServiceClient.prototype.listWorkouts =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gaintain.WorkoutService/ListWorkouts',
      request,
      metadata || {},
      methodDescriptor_WorkoutService_ListWorkouts,
      callback);
};


/**
 * @param {!proto.gaintain.WorkoutsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gaintain.Workouts>}
 *     Promise that resolves to the response
 */
proto.gaintain.WorkoutServicePromiseClient.prototype.listWorkouts =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gaintain.WorkoutService/ListWorkouts',
      request,
      metadata || {},
      methodDescriptor_WorkoutService_ListWorkouts);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gaintain.NewWorkout,
 *   !proto.gaintain.Workout>}
 */
const methodDescriptor_WorkoutService_CreateWorkout = new grpc.web.MethodDescriptor(
  '/gaintain.WorkoutService/CreateWorkout',
  grpc.web.MethodType.UNARY,
  proto.gaintain.NewWorkout,
  proto.gaintain.Workout,
  /**
   * @param {!proto.gaintain.NewWorkout} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gaintain.Workout.deserializeBinary
);


/**
 * @param {!proto.gaintain.NewWorkout} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gaintain.Workout)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gaintain.Workout>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gaintain.WorkoutServiceClient.prototype.createWorkout =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gaintain.WorkoutService/CreateWorkout',
      request,
      metadata || {},
      methodDescriptor_WorkoutService_CreateWorkout,
      callback);
};


/**
 * @param {!proto.gaintain.NewWorkout} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gaintain.Workout>}
 *     Promise that resolves to the response
 */
proto.gaintain.WorkoutServicePromiseClient.prototype.createWorkout =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gaintain.WorkoutService/CreateWorkout',
      request,
      metadata || {},
      methodDescriptor_WorkoutService_CreateWorkout);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gaintain.WorkoutRequest,
 *   !proto.gaintain.Workout>}
 */
const methodDescriptor_WorkoutService_GetWorkout = new grpc.web.MethodDescriptor(
  '/gaintain.WorkoutService/GetWorkout',
  grpc.web.MethodType.UNARY,
  proto.gaintain.WorkoutRequest,
  proto.gaintain.Workout,
  /**
   * @param {!proto.gaintain.WorkoutRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gaintain.Workout.deserializeBinary
);


/**
 * @param {!proto.gaintain.WorkoutRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gaintain.Workout)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gaintain.Workout>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gaintain.WorkoutServiceClient.prototype.getWorkout =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gaintain.WorkoutService/GetWorkout',
      request,
      metadata || {},
      methodDescriptor_WorkoutService_GetWorkout,
      callback);
};


/**
 * @param {!proto.gaintain.WorkoutRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gaintain.Workout>}
 *     Promise that resolves to the response
 */
proto.gaintain.WorkoutServicePromiseClient.prototype.getWorkout =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gaintain.WorkoutService/GetWorkout',
      request,
      metadata || {},
      methodDescriptor_WorkoutService_GetWorkout);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gaintain.Workout,
 *   !proto.gaintain.Workout>}
 */
const methodDescriptor_WorkoutService_UpdateWorkout = new grpc.web.MethodDescriptor(
  '/gaintain.WorkoutService/UpdateWorkout',
  grpc.web.MethodType.UNARY,
  proto.gaintain.Workout,
  proto.gaintain.Workout,
  /**
   * @param {!proto.gaintain.Workout} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gaintain.Workout.deserializeBinary
);


/**
 * @param {!proto.gaintain.Workout} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gaintain.Workout)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gaintain.Workout>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gaintain.WorkoutServiceClient.prototype.updateWorkout =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gaintain.WorkoutService/UpdateWorkout',
      request,
      metadata || {},
      methodDescriptor_WorkoutService_UpdateWorkout,
      callback);
};


/**
 * @param {!proto.gaintain.Workout} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gaintain.Workout>}
 *     Promise that resolves to the response
 */
proto.gaintain.WorkoutServicePromiseClient.prototype.updateWorkout =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gaintain.WorkoutService/UpdateWorkout',
      request,
      metadata || {},
      methodDescriptor_WorkoutService_UpdateWorkout);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gaintain.WorkoutRequest,
 *   !proto.gaintain.Workout>}
 */
const methodDescriptor_WorkoutService_DeleteWorkout = new grpc.web.MethodDescriptor(
  '/gaintain.WorkoutService/DeleteWorkout',
  grpc.web.MethodType.UNARY,
  proto.gaintain.WorkoutRequest,
  proto.gaintain.Workout,
  /**
   * @param {!proto.gaintain.WorkoutRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gaintain.Workout.deserializeBinary
);


/**
 * @param {!proto.gaintain.WorkoutRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gaintain.Workout)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gaintain.Workout>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gaintain.WorkoutServiceClient.prototype.deleteWorkout =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gaintain.WorkoutService/DeleteWorkout',
      request,
      metadata || {},
      methodDescriptor_WorkoutService_DeleteWorkout,
      callback);
};


/**
 * @param {!proto.gaintain.WorkoutRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gaintain.Workout>}
 *     Promise that resolves to the response
 */
proto.gaintain.WorkoutServicePromiseClient.prototype.deleteWorkout =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gaintain.WorkoutService/DeleteWorkout',
      request,
      metadata || {},
      methodDescriptor_WorkoutService_DeleteWorkout);
};


module.exports = proto.gaintain;

