# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise.proto

require 'google/protobuf'


descriptor_data = "\n\x0e\x65xercise.proto\x12\x08gaintain\"]\n\x08\x45xercise\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x11\n\tvideo_url\x18\x05 \x01(\t\"T\n\x0bNewExercise\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tvideo_url\x18\x04 \x01(\t\"2\n\tExercises\x12%\n\texercises\x18\x01 \x03(\x0b\x32\x12.gaintain.Exercise\"\x12\n\x10\x45xercisesRequest\"\x1d\n\x0f\x45xerciseRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xd3\x02\n\x0f\x45xerciseService\x12\x42\n\rListExercises\x12\x1a.gaintain.ExercisesRequest\x1a\x13.gaintain.Exercises\"\x00\x12=\n\x0e\x43reateExercise\x12\x15.gaintain.NewExercise\x1a\x12.gaintain.Exercise\"\x00\x12>\n\x0bGetExercise\x12\x19.gaintain.ExerciseRequest\x1a\x12.gaintain.Exercise\"\x00\x12:\n\x0eUpdateExercise\x12\x12.gaintain.Exercise\x1a\x12.gaintain.Exercise\"\x00\x12\x41\n\x0e\x44\x65leteExercise\x12\x19.gaintain.ExerciseRequest\x1a\x12.gaintain.Exercise\"\x00\x42\x11\x42\rExerciseProtoP\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gaintain
  Exercise = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Exercise").msgclass
  NewExercise = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.NewExercise").msgclass
  Exercises = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Exercises").msgclass
  ExercisesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.ExercisesRequest").msgclass
  ExerciseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.ExerciseRequest").msgclass
end
