# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: exercise.proto for package 'gaintain'

require 'grpc'
require 'exercise_pb'

module Gaintain
  module ExerciseService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gaintain.ExerciseService'

      rpc :ListExercises, ::Gaintain::ExercisesRequest, ::Gaintain::Exercises
      rpc :CreateExercise, ::Gaintain::NewExercise, ::Gaintain::Exercise
      rpc :GetExercise, ::Gaintain::ExerciseRequest, ::Gaintain::Exercise
      rpc :UpdateExercise, ::Gaintain::Exercise, ::Gaintain::Exercise
      rpc :DeleteExercise, ::Gaintain::ExerciseRequest, ::Gaintain::Exercise
    end

    Stub = Service.rpc_stub_class
  end
end
