# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("login.proto", :syntax => :proto3) do
    add_message "gaintain.LoginRequest" do
      optional :email, :string, 1
      optional :password, :string, 2
    end
    add_message "gaintain.LoginResponse" do
      optional :token, :string, 1
    end
  end
end

module Gaintain
  LoginRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.LoginRequest").msgclass
  LoginResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.LoginResponse").msgclass
end
