# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set.proto

require 'google/protobuf'

require 'exercise_pb'


descriptor_data = "\n\tset.proto\x12\x08gaintain\x1a\x0e\x65xercise.proto\"l\n\x03Set\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bsuperset_id\x18\x02 \x01(\t\x12\x0c\n\x04reps\x18\x03 \x01(\x05\x12\x10\n\x08position\x18\x04 \x01(\x05\x12$\n\x08\x65xercise\x18\x05 \x01(\x0b\x32\x12.gaintain.Exercise\"R\n\x06NewSet\x12\x13\n\x0b\x65xercise_id\x18\x01 \x01(\t\x12\x13\n\x0bsuperset_id\x18\x02 \x01(\t\x12\x0c\n\x04reps\x18\x03 \x01(\x05\x12\x10\n\x08position\x18\x04 \x01(\x05\"#\n\x04Sets\x12\x1b\n\x04sets\x18\x01 \x03(\x0b\x32\r.gaintain.Set\"\"\n\x0bSetsRequest\x12\x13\n\x0bsuperset_id\x18\x01 \x01(\t\"\x18\n\nSetRequest\x12\n\n\x02id\x18\x01 \x01(\t2\x83\x02\n\nSetService\x12\x33\n\x08ListSets\x12\x15.gaintain.SetsRequest\x1a\x0e.gaintain.Sets\"\x00\x12.\n\tCreateSet\x12\x10.gaintain.NewSet\x1a\r.gaintain.Set\"\x00\x12/\n\x06GetSet\x12\x14.gaintain.SetRequest\x1a\r.gaintain.Set\"\x00\x12+\n\tUpdateSet\x12\r.gaintain.Set\x1a\r.gaintain.Set\"\x00\x12\x32\n\tDeleteSet\x12\x14.gaintain.SetRequest\x1a\r.gaintain.Set\"\x00\x42\x0c\x42\x08SetProtoP\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["gaintain.Exercise", "exercise.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gaintain
  Set = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Set").msgclass
  NewSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.NewSet").msgclass
  Sets = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Sets").msgclass
  SetsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.SetsRequest").msgclass
  SetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.SetRequest").msgclass
end
