# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("set.proto", :syntax => :proto3) do
    add_message "gaintain.Set" do
      optional :id, :string, 1
      optional :exercise_id, :string, 2
      optional :superset_id, :string, 3
      optional :reps, :int32, 4
      optional :position, :int32, 5
    end
    add_message "gaintain.NewSet" do
      optional :exercise_id, :string, 1
      optional :superset_id, :string, 2
      optional :reps, :int32, 3
      optional :position, :int32, 4
    end
    add_message "gaintain.Sets" do
      repeated :sets, :message, 1, "gaintain.Set"
    end
    add_message "gaintain.SetsRequest" do
      optional :superset_id, :string, 1
    end
    add_message "gaintain.SetRequest" do
      optional :id, :string, 1
    end
  end
end

module Gaintain
  Set = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Set").msgclass
  NewSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.NewSet").msgclass
  Sets = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Sets").msgclass
  SetsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.SetsRequest").msgclass
  SetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.SetRequest").msgclass
end
