# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: set.proto for package 'gaintain'

require 'grpc'
require 'set_pb'

module Gaintain
  module SetService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gaintain.SetService'

      rpc :ListSets, ::Gaintain::SetsRequest, ::Gaintain::Sets
      rpc :CreateSet, ::Gaintain::NewSet, ::Gaintain::Set
      rpc :GetSet, ::Gaintain::SetRequest, ::Gaintain::Set
      rpc :UpdateSet, ::Gaintain::Set, ::Gaintain::Set
      rpc :DeleteSet, ::Gaintain::SetRequest, ::Gaintain::Set
    end

    Stub = Service.rpc_stub_class
  end
end
