# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: superset.proto

require 'google/protobuf'

require 'set_pb'


descriptor_data = "\n\x0esuperset.proto\x12\x08gaintain\x1a\tset.proto\"Y\n\x08Superset\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nworkout_id\x18\x02 \x01(\t\x12\x10\n\x08position\x18\x03 \x01(\x05\x12\x1b\n\x04sets\x18\x04 \x03(\x0b\x32\r.gaintain.Set\"3\n\x0bNewSuperset\x12\x12\n\nworkout_id\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x05\"2\n\tSupersets\x12%\n\tsupersets\x18\x01 \x03(\x0b\x32\x12.gaintain.Superset\"&\n\x10SupersetsRequest\x12\x12\n\nworkout_id\x18\x01 \x01(\t\"\x1d\n\x0fSupersetRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xd3\x02\n\x0fSupersetService\x12\x42\n\rListSupersets\x12\x1a.gaintain.SupersetsRequest\x1a\x13.gaintain.Supersets\"\x00\x12=\n\x0e\x43reateSuperset\x12\x15.gaintain.NewSuperset\x1a\x12.gaintain.Superset\"\x00\x12>\n\x0bGetSuperset\x12\x19.gaintain.SupersetRequest\x1a\x12.gaintain.Superset\"\x00\x12:\n\x0eUpdateSuperset\x12\x12.gaintain.Superset\x1a\x12.gaintain.Superset\"\x00\x12\x41\n\x0e\x44\x65leteSuperset\x12\x19.gaintain.SupersetRequest\x1a\x12.gaintain.Superset\"\x00\x42\x11\x42\rSupersetProtoP\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["gaintain.Set", "set.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gaintain
  Superset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Superset").msgclass
  NewSuperset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.NewSuperset").msgclass
  Supersets = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Supersets").msgclass
  SupersetsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.SupersetsRequest").msgclass
  SupersetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.SupersetRequest").msgclass
end
