# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'


descriptor_data = "\n\nuser.proto\x12\x08gaintain\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"8\n\x07NewUser\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"G\n\nModifyUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"&\n\x05Users\x12\x1d\n\x05users\x18\x01 \x03(\x0b\x32\x0e.gaintain.User\"\x0e\n\x0cUsersRequest\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\t2\x99\x02\n\x0bUserService\x12\x36\n\tListUsers\x12\x16.gaintain.UsersRequest\x1a\x0f.gaintain.Users\"\x00\x12\x31\n\nCreateUser\x12\x11.gaintain.NewUser\x1a\x0e.gaintain.User\"\x00\x12\x32\n\x07GetUser\x12\x15.gaintain.UserRequest\x1a\x0e.gaintain.User\"\x00\x12\x34\n\nUpdateUser\x12\x14.gaintain.ModifyUser\x1a\x0e.gaintain.User\"\x00\x12\x35\n\nDeleteUser\x12\x15.gaintain.UserRequest\x1a\x0e.gaintain.User\"\x00\x42\rB\tUserProtoP\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gaintain
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.User").msgclass
  NewUser = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.NewUser").msgclass
  ModifyUser = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.ModifyUser").msgclass
  Users = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Users").msgclass
  UsersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.UsersRequest").msgclass
  UserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.UserRequest").msgclass
end
