# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "gaintain.User" do
      optional :id, :string, 1
      optional :email, :string, 2
      optional :name, :string, 3
    end
    add_message "gaintain.NewUser" do
      optional :email, :string, 1
      optional :name, :string, 2
      optional :password, :string, 3
    end
    add_message "gaintain.ModifyUser" do
      optional :id, :string, 1
      optional :email, :string, 2
      optional :name, :string, 3
      optional :password, :string, 4
    end
    add_message "gaintain.Users" do
      repeated :users, :message, 1, "gaintain.User"
    end
    add_message "gaintain.UsersRequest" do
    end
    add_message "gaintain.UserRequest" do
      optional :id, :string, 1
    end
  end
end

module Gaintain
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.User").msgclass
  NewUser = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.NewUser").msgclass
  ModifyUser = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.ModifyUser").msgclass
  Users = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Users").msgclass
  UsersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.UsersRequest").msgclass
  UserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.UserRequest").msgclass
end
