# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workout.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("workout.proto", :syntax => :proto3) do
    add_message "gaintain.Workout" do
      optional :id, :string, 1
      optional :user_id, :string, 2
      optional :name, :string, 3
      optional :description, :string, 4
    end
    add_message "gaintain.NewWorkout" do
      optional :user_id, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
    end
    add_message "gaintain.Workouts" do
      repeated :workouts, :message, 1, "gaintain.Workout"
    end
    add_message "gaintain.WorkoutsRequest" do
    end
    add_message "gaintain.WorkoutRequest" do
      optional :id, :string, 1
    end
  end
end

module Gaintain
  Workout = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Workout").msgclass
  NewWorkout = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.NewWorkout").msgclass
  Workouts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Workouts").msgclass
  WorkoutsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.WorkoutsRequest").msgclass
  WorkoutRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.WorkoutRequest").msgclass
end
