# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: workout.proto for package 'gaintain'

require 'grpc'
require 'workout_pb'

module Gaintain
  module WorkoutService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gaintain.WorkoutService'

      rpc :ListWorkouts, ::Gaintain::WorkoutsRequest, ::Gaintain::Workouts
      rpc :CreateWorkout, ::Gaintain::NewWorkout, ::Gaintain::Workout
      rpc :GetWorkout, ::Gaintain::WorkoutRequest, ::Gaintain::Workout
      rpc :UpdateWorkout, ::Gaintain::Workout, ::Gaintain::Workout
      rpc :DeleteWorkout, ::Gaintain::WorkoutRequest, ::Gaintain::Workout
    end

    Stub = Service.rpc_stub_class
  end
end
