# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workout.proto

require 'google/protobuf'

require 'superset_pb'


descriptor_data = "\n\rworkout.proto\x12\x08gaintain\x1a\x0esuperset.proto\"p\n\x07Workout\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12%\n\tsupersets\x18\x05 \x03(\x0b\x32\x12.gaintain.Superset\"@\n\nNewWorkout\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"/\n\x08Workouts\x12#\n\x08workouts\x18\x01 \x03(\x0b\x32\x11.gaintain.Workout\"\x11\n\x0fWorkoutsRequest\"\x1c\n\x0eWorkoutRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xc3\x02\n\x0eWorkoutService\x12?\n\x0cListWorkouts\x12\x19.gaintain.WorkoutsRequest\x1a\x12.gaintain.Workouts\"\x00\x12:\n\rCreateWorkout\x12\x14.gaintain.NewWorkout\x1a\x11.gaintain.Workout\"\x00\x12;\n\nGetWorkout\x12\x18.gaintain.WorkoutRequest\x1a\x11.gaintain.Workout\"\x00\x12\x37\n\rUpdateWorkout\x12\x11.gaintain.Workout\x1a\x11.gaintain.Workout\"\x00\x12>\n\rDeleteWorkout\x12\x18.gaintain.WorkoutRequest\x1a\x11.gaintain.Workout\"\x00\x42\x10\x42\x0cWorkoutProtoP\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["gaintain.Superset", "superset.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gaintain
  Workout = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Workout").msgclass
  NewWorkout = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.NewWorkout").msgclass
  Workouts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.Workouts").msgclass
  WorkoutsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.WorkoutsRequest").msgclass
  WorkoutRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gaintain.WorkoutRequest").msgclass
end
