/**
 * @fileoverview gRPC-Web generated client stub for gaintain
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.1
// source: user.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as user_pb from './user_pb';


export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorListUsers = new grpcWeb.MethodDescriptor(
    '/gaintain.UserService/ListUsers',
    grpcWeb.MethodType.UNARY,
    user_pb.UsersRequest,
    user_pb.Users,
    (request: user_pb.UsersRequest) => {
      return request.serializeBinary();
    },
    user_pb.Users.deserializeBinary
  );

  listUsers(
    request: user_pb.UsersRequest,
    metadata: grpcWeb.Metadata | null): Promise<user_pb.Users>;

  listUsers(
    request: user_pb.UsersRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_pb.Users) => void): grpcWeb.ClientReadableStream<user_pb.Users>;

  listUsers(
    request: user_pb.UsersRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_pb.Users) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gaintain.UserService/ListUsers',
        request,
        metadata || {},
        this.methodDescriptorListUsers,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gaintain.UserService/ListUsers',
    request,
    metadata || {},
    this.methodDescriptorListUsers);
  }

  methodDescriptorCreateUser = new grpcWeb.MethodDescriptor(
    '/gaintain.UserService/CreateUser',
    grpcWeb.MethodType.UNARY,
    user_pb.NewUser,
    user_pb.User,
    (request: user_pb.NewUser) => {
      return request.serializeBinary();
    },
    user_pb.User.deserializeBinary
  );

  createUser(
    request: user_pb.NewUser,
    metadata: grpcWeb.Metadata | null): Promise<user_pb.User>;

  createUser(
    request: user_pb.NewUser,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_pb.User) => void): grpcWeb.ClientReadableStream<user_pb.User>;

  createUser(
    request: user_pb.NewUser,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_pb.User) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gaintain.UserService/CreateUser',
        request,
        metadata || {},
        this.methodDescriptorCreateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gaintain.UserService/CreateUser',
    request,
    metadata || {},
    this.methodDescriptorCreateUser);
  }

  methodDescriptorGetUser = new grpcWeb.MethodDescriptor(
    '/gaintain.UserService/GetUser',
    grpcWeb.MethodType.UNARY,
    user_pb.UserRequest,
    user_pb.User,
    (request: user_pb.UserRequest) => {
      return request.serializeBinary();
    },
    user_pb.User.deserializeBinary
  );

  getUser(
    request: user_pb.UserRequest,
    metadata: grpcWeb.Metadata | null): Promise<user_pb.User>;

  getUser(
    request: user_pb.UserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_pb.User) => void): grpcWeb.ClientReadableStream<user_pb.User>;

  getUser(
    request: user_pb.UserRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_pb.User) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gaintain.UserService/GetUser',
        request,
        metadata || {},
        this.methodDescriptorGetUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gaintain.UserService/GetUser',
    request,
    metadata || {},
    this.methodDescriptorGetUser);
  }

  methodDescriptorUpdateUser = new grpcWeb.MethodDescriptor(
    '/gaintain.UserService/UpdateUser',
    grpcWeb.MethodType.UNARY,
    user_pb.ModifyUser,
    user_pb.User,
    (request: user_pb.ModifyUser) => {
      return request.serializeBinary();
    },
    user_pb.User.deserializeBinary
  );

  updateUser(
    request: user_pb.ModifyUser,
    metadata: grpcWeb.Metadata | null): Promise<user_pb.User>;

  updateUser(
    request: user_pb.ModifyUser,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_pb.User) => void): grpcWeb.ClientReadableStream<user_pb.User>;

  updateUser(
    request: user_pb.ModifyUser,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_pb.User) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gaintain.UserService/UpdateUser',
        request,
        metadata || {},
        this.methodDescriptorUpdateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gaintain.UserService/UpdateUser',
    request,
    metadata || {},
    this.methodDescriptorUpdateUser);
  }

  methodDescriptorDeleteUser = new grpcWeb.MethodDescriptor(
    '/gaintain.UserService/DeleteUser',
    grpcWeb.MethodType.UNARY,
    user_pb.UserRequest,
    user_pb.User,
    (request: user_pb.UserRequest) => {
      return request.serializeBinary();
    },
    user_pb.User.deserializeBinary
  );

  deleteUser(
    request: user_pb.UserRequest,
    metadata: grpcWeb.Metadata | null): Promise<user_pb.User>;

  deleteUser(
    request: user_pb.UserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_pb.User) => void): grpcWeb.ClientReadableStream<user_pb.User>;

  deleteUser(
    request: user_pb.UserRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_pb.User) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gaintain.UserService/DeleteUser',
        request,
        metadata || {},
        this.methodDescriptorDeleteUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gaintain.UserService/DeleteUser',
    request,
    metadata || {},
    this.methodDescriptorDeleteUser);
  }

}

